// <auto-generated />
namespace IdealKarkas.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Edit2105 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit2105));
        
        string IMigrationMetadata.Id
        {
            get { return "202405212020525_Edit2105"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
